# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_tags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
