# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-02 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20161219_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='number_of_options',
            field=models.IntegerField(),
        ),
    ]
