# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20170101_0635'),
        ('qna', '0003_auto_20170102_0600'),
    ]

    operations = [
    ]
