# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-28 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_merge_20170105_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='options',
        ),
        migrations.AddField(
            model_name='options',
            name='option1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option10',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option6',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option7',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option8',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='option9',
            field=models.TextField(null=True),
        ),
    ]
