# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-22 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=login.models.upload_to),
        ),
    ]
