# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-22 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
