# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-02 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0007_auto_20170228_0958'),
        ('login', '0003_auto_20170222_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_categories',
            field=models.ManyToManyField(blank=True, to='qna.Category'),
        ),
    ]
